# Generated by Django 5.0.8 on 2025-10-19 12:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoExpediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do Tipo')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Tipo de Expediente',
                'verbose_name_plural': 'Tipos de Expediente',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_protocolo', models.CharField(help_text='Ex: 20250200003', max_length=20, unique=True, verbose_name='Número de Protocolo')),
                ('origem', models.CharField(blank=True, help_text='Ex: Departamento RH', max_length=200, verbose_name='Origem')),
                ('remetente', models.CharField(blank=True, help_text='Nome do remetente', max_length=200, verbose_name='Remetente')),
                ('assunto', models.CharField(help_text='Resumo do assunto da correspondência', max_length=300, verbose_name='Assunto')),
                ('descricao', models.TextField(blank=True, help_text='Descrição detalhada da correspondência (opcional)', verbose_name='Descrição')),
                ('telefone', models.CharField(blank=True, help_text='Ex: +258 82 123 4567', max_length=20, verbose_name='Telefone')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('submetido', 'Submetido'), ('em_analise', 'Em Análise'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado'), ('arquivado', 'Arquivado')], default='rascunho', max_length=20, verbose_name='Status')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('data_submissao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Submissão')),
                ('data_aprovacao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Aprovação')),
                ('rascunho', models.BooleanField(default=True, verbose_name='É Rascunho')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expedientes_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('estado_atual', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.estadodocumento', verbose_name='Estado Atual')),
                ('membros_envolvidos', models.ManyToManyField(blank=True, related_name='expedientes_entrada', to=settings.AUTH_USER_MODEL, verbose_name='Membros Envolvidos')),
                ('sector_responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expedientes_responsavel', to='core.sector', verbose_name='Sector Responsável')),
                ('sectores_envolvidos', models.ManyToManyField(blank=True, related_name='expedientes_entrada', to='core.sector', verbose_name='Sectores Envolvidos')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='entrada.tipoexpediente', verbose_name='Tipo de Expediente')),
            ],
            options={
                'verbose_name': 'Expediente',
                'verbose_name_plural': 'Expedientes',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='AnexoExpediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='expedientes/anexos/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png'])], verbose_name='Arquivo')),
                ('nome_original', models.CharField(max_length=255, verbose_name='Nome Original')),
                ('tamanho', models.PositiveIntegerField(verbose_name='Tamanho (bytes)')),
                ('tipo_mime', models.CharField(max_length=100, verbose_name='Tipo MIME')),
                ('descricao', models.CharField(blank=True, max_length=200, verbose_name='Descrição')),
                ('data_upload', models.DateTimeField(auto_now_add=True, verbose_name='Data de Upload')),
                ('upload_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Upload por')),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='entrada.expediente', verbose_name='Expediente')),
            ],
            options={
                'verbose_name': 'Anexo de Expediente',
                'verbose_name_plural': 'Anexos de Expediente',
                'ordering': ['-data_upload'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoExpediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(max_length=100, verbose_name='Ação')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('data_acao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Ação')),
                ('estado_anterior', models.CharField(blank=True, max_length=50, verbose_name='Estado Anterior')),
                ('estado_novo', models.CharField(blank=True, max_length=50, verbose_name='Estado Novo')),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='entrada.expediente', verbose_name='Expediente')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Histórico de Expediente',
                'verbose_name_plural': 'Histórico de Expedientes',
                'ordering': ['-data_acao'],
            },
        ),
    ]
