# Generated by Django 5.0.8 on 2025-10-19 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrada', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do Tipo')),
                ('categoria', models.CharField(choices=[('carta', 'Carta'), ('requerimento', 'Requerimento'), ('informacao', 'Informação'), ('reclamacao', 'Reclamação'), ('denuncia', 'Denúncia'), ('oficio', 'Ofício'), ('convite', 'Convite'), ('circular', 'Circular'), ('memorando', 'Memorando'), ('relatorio', 'Relatório'), ('contrato', 'Contrato'), ('proposta', 'Proposta'), ('licitacao', 'Licitação'), ('certificacao', 'Certificação'), ('outro', 'Outro')], max_length=20, verbose_name='Categoria')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('prazo_resposta', models.PositiveIntegerField(help_text='Prazo em dias úteis', verbose_name='Prazo de Resposta')),
                ('prioridade_padrao', models.CharField(choices=[('baixa', 'Baixa'), ('normal', 'Normal'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='normal', max_length=10, verbose_name='Prioridade Padrão')),
                ('requer_anexos', models.BooleanField(default=False, verbose_name='Requer Anexos')),
                ('campos_obrigatorios', models.JSONField(default=list, verbose_name='Campos Obrigatórios')),
                ('template_resposta', models.TextField(blank=True, null=True, verbose_name='Template de Resposta')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tipos_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Tipo de Documento',
                'verbose_name_plural': 'Tipos de Documento',
                'ordering': ['nome'],
            },
        ),
        migrations.AlterField(
            model_name='expediente',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='entrada.tipodocumento', verbose_name='Tipo de Documento'),
        ),
        migrations.DeleteModel(
            name='TipoExpediente',
        ),
    ]
