# Generated by Django 5.0.2 on 2025-10-19 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrada', '0002_tipodocumento_alter_expediente_tipo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipodocumento',
            name='campos_obrigatorios',
        ),
    ]
