# Generated by Django 5.0.2 on 2025-10-19 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_email_enviado_to_notificacao'),
        ('entrada', '0003_remove_tipodocumento_campos_obrigatorios'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='anexoexpediente',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='confidencial',
            field=models.BooleanField(default=False, verbose_name='Confidencial'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='conteudo',
            field=models.TextField(blank=True, help_text='Conteúdo detalhado do documento', verbose_name='Conteúdo'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='data_limite',
            field=models.DateField(blank=True, help_text='Prazo para resposta', null=True, verbose_name='Data Limite'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='data_recebido',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data Recebido'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='numero_paginas',
            field=models.PositiveIntegerField(default=1, verbose_name='Número de Páginas'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações Internas'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='prioridade',
            field=models.CharField(choices=[('baixa', 'Baixa'), ('normal', 'Normal'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='normal', max_length=10, verbose_name='Prioridade'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='recebido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_recebidos', to=settings.AUTH_USER_MODEL, verbose_name='Recebido por'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='requer_resposta',
            field=models.BooleanField(default=True, verbose_name='Requer Resposta'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='valor_monetario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor Monetário'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='origem',
            field=models.CharField(choices=[('secretaria', 'Secretaria'), ('portal', 'Portal Online'), ('quiosque', 'Quiosque'), ('email', 'Email'), ('fax', 'Fax'), ('correio', 'Correio'), ('pessoal', 'Entrega Pessoal')], default='secretaria', help_text='Como o documento entrou no sistema', max_length=20, verbose_name='Origem'),
        ),
        migrations.CreateModel(
            name='MovimentacaoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('data_movimentacao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Movimentação')),
                ('tipo_movimentacao', models.CharField(choices=[('encaminhamento', 'Encaminhamento'), ('devolucao', 'Devolução'), ('recebimento', 'Recebimento'), ('conclusao', 'Conclusão'), ('arquivamento', 'Arquivamento'), ('reativacao', 'Reativação')], max_length=20, verbose_name='Tipo de Movimentação')),
                ('automatica', models.BooleanField(default=False, verbose_name='Automática')),
                ('notificacao_enviada', models.BooleanField(default=False, verbose_name='Notificação Enviada')),
                ('data_notificacao', models.DateTimeField(blank=True, null=True, verbose_name='Data da Notificação')),
                ('de_sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_enviadas', to='core.sector', verbose_name='De Sector')),
                ('de_utilizador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_enviadas', to=settings.AUTH_USER_MODEL, verbose_name='De Utilizador')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='entrada.expediente', verbose_name='Documento')),
                ('estado_anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_anterior', to='core.estadodocumento', verbose_name='Estado Anterior')),
                ('estado_novo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_novo', to='core.estadodocumento', verbose_name='Estado Novo')),
                ('para_sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_recebidas', to='core.sector', verbose_name='Para Sector')),
                ('para_utilizador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_recebidas', to=settings.AUTH_USER_MODEL, verbose_name='Para Utilizador')),
            ],
            options={
                'verbose_name': 'Movimentação de Documento',
                'verbose_name_plural': 'Movimentações de Documentos',
                'ordering': ['-data_movimentacao'],
            },
        ),
    ]
