# Generated by Django 5.0.2 on 2025-10-19 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrada', '0004_add_checklist_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='referencia',
            field=models.CharField(blank=True, help_text='Referência do documento recebido (ex: Ofício nº 123/2025)', max_length=200, verbose_name='Referência do Documento'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='numero_protocolo',
            field=models.CharField(help_text='Formato: AAAAMMXXXXX (gerado automaticamente)', max_length=15, unique=True, verbose_name='Número de Protocolo'),
        ),
    ]
