# Generated by Django 5.0.2 on 2025-10-19 21:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrada', '0005_add_referencia_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='utilizador_atual',
            field=models.ForeignKey(blank=True, help_text='Utilizador que está atualmente com o documento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_posse', to=settings.AUTH_USER_MODEL, verbose_name='Utilizador Atual'),
        ),
    ]
