# Generated by Django 5.0.8 on 2025-10-20 20:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrada', '0006_add_utilizador_atual'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacaodocumento',
            name='tipo_movimentacao',
            field=models.CharField(choices=[('encaminhamento', 'Encaminhamento'), ('devolucao', 'Devolução'), ('recebimento', 'Recebimento'), ('conclusao', 'Conclusão'), ('arquivamento', 'Arquivamento'), ('reativacao', 'Reativação'), ('parecer', 'Parecer')], max_length=20, verbose_name='Tipo de Movimentação'),
        ),
        migrations.CreateModel(
            name='ParecerExpediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_parecer', models.CharField(choices=[('favoravel', 'Favorável'), ('desfavoravel', 'Desfavorável'), ('com_reservas', 'Com Reservas'), ('informativo', 'Informativo'), ('recomendacao', 'Recomendação'), ('observacao', 'Observação')], max_length=20, verbose_name='Tipo de Parecer')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título do Parecer')),
                ('conteudo', models.TextField(verbose_name='Conteúdo do Parecer')),
                ('recomendacoes', models.TextField(blank=True, verbose_name='Recomendações')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações Adicionais')),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('normal', 'Normal'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='normal', max_length=10, verbose_name='Prioridade')),
                ('data_parecer', models.DateTimeField(auto_now_add=True, verbose_name='Data do Parecer')),
                ('data_limite', models.DateTimeField(blank=True, null=True, verbose_name='Data Limite para Implementação')),
                ('implementado', models.BooleanField(default=False, verbose_name='Implementado')),
                ('data_implementacao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Implementação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pareceres', to='entrada.expediente', verbose_name='Expediente')),
                ('implementado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pareceres_implementados', to=settings.AUTH_USER_MODEL, verbose_name='Implementado por')),
                ('parecerista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pareceres_emitidos', to=settings.AUTH_USER_MODEL, verbose_name='Parecerista')),
            ],
            options={
                'verbose_name': 'Parecer de Expediente',
                'verbose_name_plural': 'Pareceres de Expedientes',
                'ordering': ['-data_parecer'],
            },
        ),
    ]
