# Generated by Django 5.0.8 on 2025-11-05 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrada', '0007_alter_movimentacaodocumento_tipo_movimentacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='assunto',
            field=models.CharField(help_text='Resumo do assunto do processo', max_length=300, verbose_name='Assunto'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='descricao',
            field=models.TextField(blank=True, help_text='Descrição detalhada do processo (opcional)', verbose_name='Descrição'),
        ),
    ]
