# Generated by Django 5.0.8 on 2025-10-19 11:21

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(help_text='Email único para login no sistema', max_length=254, unique=True, verbose_name='Email')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='Nome')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='Sobrenome')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Formato de telefone inválido. Use: +258 82 123 4567', regex='^\\+?1?\\d{9,15}$')], verbose_name='Telefone')),
                ('cargo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cargo')),
                ('ativo', models.BooleanField(default=True, help_text='Se o utilizador está ativo no sistema', verbose_name='Ativo')),
                ('tipo_utilizador', models.CharField(choices=[('admin', 'Administrador do Sistema'), ('pca', 'PCA'), ('secretaria', 'Secretaria'), ('chefe', 'Chefe de Sector'), ('colaborador', 'Colaborador'), ('externo', 'Utilizador Externo')], default='colaborador', help_text='Papel do utilizador no sistema', max_length=20, verbose_name='Tipo de Utilizador')),
                ('ultimo_acesso', models.DateTimeField(blank=True, null=True, verbose_name='Último Acesso')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/%Y/%m/', verbose_name='Avatar')),
                ('biografia', models.TextField(blank=True, null=True, verbose_name='Biografia')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('genero', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=10, null=True, verbose_name='Género')),
                ('endereco', models.TextField(blank=True, null=True, verbose_name='Endereço')),
                ('codigo_postal', models.CharField(blank=True, max_length=10, null=True, verbose_name='Código Postal')),
                ('cidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade')),
                ('pais', models.CharField(default='Moçambique', max_length=100, verbose_name='País')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='custom_user_set', related_query_name='custom_user', to='auth.group', verbose_name='groups')),
                ('sector_atual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utilizadores', to='core.sector', verbose_name='Sector Atual')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='custom_user_set', related_query_name='custom_user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilizador',
                'verbose_name_plural': 'Utilizadores',
                'ordering': ['first_name', 'last_name'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='PerfilUtilizador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receber_notificacoes_email', models.BooleanField(default=True, verbose_name='Receber Notificações por Email')),
                ('receber_notificacoes_push', models.BooleanField(default=True, verbose_name='Receber Notificações Push')),
                ('receber_newsletter', models.BooleanField(default=False, verbose_name='Receber Newsletter')),
                ('tema_preferido', models.CharField(choices=[('light', 'Claro'), ('dark', 'Escuro'), ('auto', 'Automático')], default='light', max_length=20, verbose_name='Tema Preferido')),
                ('idioma_preferido', models.CharField(choices=[('pt-pt', 'Português'), ('en', 'English')], default='pt-pt', max_length=10, verbose_name='Idioma Preferido')),
                ('timezone', models.CharField(default='Africa/Maputo', max_length=50, verbose_name='Fuso Horário')),
                ('perfil_publico', models.BooleanField(default=False, verbose_name='Perfil Público')),
                ('mostrar_email', models.BooleanField(default=False, verbose_name='Mostrar Email')),
                ('mostrar_telefone', models.BooleanField(default=False, verbose_name='Mostrar Telefone')),
                ('horario_trabalho_inicio', models.TimeField(blank=True, null=True, verbose_name='Horário de Trabalho - Início')),
                ('horario_trabalho_fim', models.TimeField(blank=True, null=True, verbose_name='Horário de Trabalho - Fim')),
                ('dias_trabalho', models.CharField(default='1,2,3,4,5', help_text='Dias da semana separados por vírgula (1=Segunda, 7=Domingo)', max_length=20, verbose_name='Dias de Trabalho')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL, verbose_name='Utilizador')),
            ],
            options={
                'verbose_name': 'Perfil de Utilizador',
                'verbose_name_plural': 'Perfis de Utilizadores',
            },
        ),
        migrations.CreateModel(
            name='HierarquiaUtilizador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_relacao', models.CharField(choices=[('chefe_direto', 'Chefe Direto'), ('supervisor', 'Supervisor'), ('mentor', 'Mentor'), ('substituto', 'Substituto')], default='chefe_direto', max_length=20, verbose_name='Tipo de Relação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_inicio', models.DateTimeField(auto_now_add=True, verbose_name='Data de Início')),
                ('data_fim', models.DateTimeField(blank=True, null=True, verbose_name='Data de Fim')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('subordinado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='superiores_diretos', to=settings.AUTH_USER_MODEL, verbose_name='Subordinado')),
                ('superior', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subordinados_diretos', to=settings.AUTH_USER_MODEL, verbose_name='Superior')),
            ],
            options={
                'verbose_name': 'Hierarquia de Utilizador',
                'verbose_name_plural': 'Hierarquias de Utilizadores',
                'ordering': ['-data_inicio'],
                'unique_together': {('superior', 'subordinado', 'tipo_relacao')},
            },
        ),
    ]
