# Generated by Django 5.0.8 on 2025-10-19 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, help_text='Campo não utilizado para login. Use email.', max_length=150, null=True, verbose_name='Username'),
        ),
    ]
