# Generated by Django 5.0.2 on 2025-10-23 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_add_email_enviado_to_notificacao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoRelatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do Tipo')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('tipo_relatorio', models.CharField(choices=[('documentos_sector', 'Documentos por Sector'), ('tempo_resposta', 'Tempo de Resposta'), ('estados_documentos', 'Estados de Documentos'), ('comunicacao_sector', 'Comunicação por Sector'), ('atividade_utilizadores', 'Atividade de Utilizadores'), ('eficiencia_sector', 'Eficiência por Sector'), ('utilizacao_sistema', 'Utilização do Sistema'), ('documentos_periodo', 'Documentos por Período'), ('performance_geral', 'Performance Geral'), ('customizado', 'Relatório Customizado')], max_length=30, verbose_name='Tipo de Relatório')),
                ('template', models.CharField(help_text='Caminho para o template do relatório', max_length=200, verbose_name='Template')),
                ('parametros_obrigatorios', models.JSONField(default=list, help_text='Lista de parâmetros obrigatórios para este tipo de relatório', verbose_name='Parâmetros Obrigatórios')),
                ('parametros_opcionais', models.JSONField(default=list, help_text='Lista de parâmetros opcionais para este tipo de relatório', verbose_name='Parâmetros Opcionais')),
                ('formato_saida', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV'), ('html', 'HTML'), ('json', 'JSON')], default='pdf', max_length=10, verbose_name='Formato de Saída')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Tipo de Relatório',
                'verbose_name_plural': 'Tipos de Relatórios',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoRelatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Relatório')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('parametros', models.JSONField(default=dict, help_text='Parâmetros configurados para este relatório', verbose_name='Parâmetros')),
                ('filtros', models.JSONField(default=dict, help_text='Filtros aplicados aos dados', verbose_name='Filtros')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('publico', models.BooleanField(default=False, help_text='Se outros utilizadores podem usar este relatório', verbose_name='Público')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_ultima_execucao', models.DateTimeField(blank=True, null=True, verbose_name='Data da Última Execução')),
                ('execucoes_count', models.PositiveIntegerField(default=0, verbose_name='Número de Execuções')),
                ('sector', models.ForeignKey(blank=True, help_text='Sector específico (deixe vazio para todos)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.sector', verbose_name='Sector')),
                ('utilizador_criador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relatorios_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('tipo_relatorio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='relatorios.tiporelatorio', verbose_name='Tipo de Relatório')),
            ],
            options={
                'verbose_name': 'Configuração de Relatório',
                'verbose_name_plural': 'Configurações de Relatórios',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Dashboard')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('widgets', models.JSONField(default=list, help_text='Lista de widgets configurados', verbose_name='Widgets')),
                ('layout', models.JSONField(default=dict, help_text='Configuração do layout do dashboard', verbose_name='Layout')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('publico', models.BooleanField(default=False, help_text='Se outros utilizadores podem ver este dashboard', verbose_name='Público')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('sector', models.ForeignKey(blank=True, help_text='Sector específico (deixe vazio para todos)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.sector', verbose_name='Sector')),
                ('utilizador_criador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dashboards_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Dashboard',
                'verbose_name_plural': 'Dashboards',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='ExecucaoRelatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_execucao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Execução')),
                ('data_conclusao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Conclusão')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('processando', 'Processando'), ('concluido', 'Concluído'), ('erro', 'Erro'), ('cancelado', 'Cancelado')], default='pendente', max_length=20, verbose_name='Status')),
                ('ficheiro_gerado', models.FileField(blank=True, null=True, upload_to='relatorios/', verbose_name='Ficheiro Gerado')),
                ('parametros_utilizados', models.JSONField(default=dict, verbose_name='Parâmetros Utilizados')),
                ('filtros_utilizados', models.JSONField(default=dict, verbose_name='Filtros Utilizados')),
                ('erro', models.TextField(blank=True, help_text='Descrição do erro, se houver', verbose_name='Erro')),
                ('tamanho_ficheiro', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tamanho do Ficheiro (bytes)')),
                ('registros_processados', models.PositiveIntegerField(blank=True, null=True, verbose_name='Registros Processados')),
                ('relatorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execucoes', to='relatorios.configuracaorelatorio', verbose_name='Relatório')),
                ('utilizador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='execucoes_relatorios', to=settings.AUTH_USER_MODEL, verbose_name='Utilizador')),
            ],
            options={
                'verbose_name': 'Execução de Relatório',
                'verbose_name_plural': 'Execuções de Relatórios',
                'ordering': ['-data_execucao'],
            },
        ),
        migrations.CreateModel(
            name='WidgetDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_widget', models.CharField(choices=[('contador', 'Contador'), ('grafico_barras', 'Gráfico de Barras'), ('grafico_pizza', 'Gráfico de Pizza'), ('grafico_linha', 'Gráfico de Linha'), ('grafico_area', 'Gráfico de Área'), ('tabela', 'Tabela'), ('lista', 'Lista'), ('metricas', 'Métricas'), ('calendario', 'Calendário'), ('atividade', 'Atividade Recente')], max_length=20, verbose_name='Tipo de Widget')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('posicao', models.JSONField(default=dict, help_text='Posição do widget no grid (x, y, width, height)', verbose_name='Posição')),
                ('parametros', models.JSONField(default=dict, help_text='Parâmetros específicos do widget', verbose_name='Parâmetros')),
                ('tamanho', models.JSONField(default=dict, help_text='Tamanho do widget (width, height)', verbose_name='Tamanho')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets_dashboard', to='relatorios.dashboard', verbose_name='Dashboard')),
            ],
            options={
                'verbose_name': 'Widget de Dashboard',
                'verbose_name_plural': 'Widgets de Dashboard',
                'ordering': ['dashboard', 'ordem'],
            },
        ),
    ]
