# Generated by Django 5.0.8 on 2025-10-19 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnexoDespacho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ficheiro', models.FileField(upload_to='despachos/%Y/%m/', verbose_name='Ficheiro')),
                ('nome_original', models.CharField(max_length=255, verbose_name='Nome Original')),
                ('tamanho', models.PositiveIntegerField(verbose_name='Tamanho (bytes)')),
                ('tipo_mime', models.CharField(blank=True, max_length=100, verbose_name='Tipo MIME')),
                ('data_upload', models.DateTimeField(auto_now_add=True, verbose_name='Data de Upload')),
            ],
            options={
                'verbose_name': 'Anexo de Despacho',
                'verbose_name_plural': 'Anexos de Despachos',
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(max_length=100, unique=True, verbose_name='Chave')),
                ('valor', models.TextField(verbose_name='Valor')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('tipo', models.CharField(choices=[('string', 'Texto'), ('int', 'Número Inteiro'), ('bool', 'Booleano'), ('json', 'JSON')], default='string', max_length=10, verbose_name='Tipo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
            options={
                'verbose_name': 'Configuração do Sistema',
                'verbose_name_plural': 'Configurações do Sistema',
                'ordering': ['chave'],
            },
        ),
        migrations.CreateModel(
            name='DespachoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('tipo', models.CharField(choices=[('despacho', 'Despacho'), ('parecer', 'Parecer'), ('comentario', 'Comentário')], max_length=20, verbose_name='Tipo')),
                ('conteudo', models.TextField(verbose_name='Conteúdo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('visivel_para', models.CharField(choices=[('todos', 'Todos'), ('chefes', 'Apenas Chefes e PCA'), ('pca', 'Apenas PCA')], default='todos', max_length=20, verbose_name='Visível Para')),
                ('editado', models.BooleanField(default=False, verbose_name='Editado')),
            ],
            options={
                'verbose_name': 'Despacho/Parecer/Comentário',
                'verbose_name_plural': 'Despachos/Pareceres/Comentários',
                'ordering': ['data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='EstadoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Nome')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('cor', models.CharField(max_length=7, verbose_name='Cor (código hex)')),
                ('ordem', models.PositiveIntegerField(verbose_name='Ordem')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('requer_acao', models.BooleanField(default=False, verbose_name='Requer Ação')),
            ],
            options={
                'verbose_name': 'Estado de Documento',
                'verbose_name_plural': 'Estados de Documentos',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('tipo', models.CharField(choices=[('documento_novo', 'Novo Documento'), ('documento_encaminhado', 'Documento Encaminhado'), ('documento_recebido', 'Documento Recebido'), ('documento_concluido', 'Documento Concluído'), ('documento_arquivado', 'Documento Arquivado'), ('documento_devolvido', 'Documento Devolvido'), ('mensagem_nova', 'Nova Mensagem')], max_length=50, verbose_name='Tipo')),
                ('lida', models.BooleanField(default=False, verbose_name='Lida')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_lida', models.DateTimeField(blank=True, null=True, verbose_name='Data de Leitura')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('prioridade', models.CharField(choices=[('normal', 'Normal'), ('urgente', 'Urgente')], default='normal', max_length=10, verbose_name='Prioridade')),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
            ],
            options={
                'verbose_name': 'Sector',
                'verbose_name_plural': 'Sectores',
                'ordering': ['nome'],
            },
        ),
    ]
