# Generated by Django 5.0.8 on 2025-10-19 11:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='despachodocumento',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despachos_criados', to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
        migrations.AddField(
            model_name='despachodocumento',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='anexodespacho',
            name='despacho',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='core.despachodocumento', verbose_name='Despacho'),
        ),
        migrations.AddField(
            model_name='notificacao',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='notificacao',
            name='destinatario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes_recebidas', to=settings.AUTH_USER_MODEL, verbose_name='Destinatário'),
        ),
        migrations.AddField(
            model_name='notificacao',
            name='remetente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes_enviadas', to=settings.AUTH_USER_MODEL, verbose_name='Remetente'),
        ),
        migrations.AddField(
            model_name='sector',
            name='chefe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sectores_chefiados', to=settings.AUTH_USER_MODEL, verbose_name='Chefe'),
        ),
        migrations.AddField(
            model_name='sector',
            name='chefe_substituto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sectores_substituicao', to=settings.AUTH_USER_MODEL, verbose_name='Chefe Substituto'),
        ),
    ]
