# Generated by Django 5.0.2 on 2025-10-19 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacao',
            name='email_enviado',
            field=models.BooleanField(default=False, verbose_name='Email Enviado'),
        ),
    ]
