# Generated by Django 5.0.8 on 2025-11-11 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_email_enviado_to_notificacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacao',
            name='tipo',
            field=models.CharField(choices=[('documento_novo', 'Novo Documento'), ('documento_encaminhado', 'Documento Encaminhado'), ('documento_recebido', 'Documento Recebido'), ('documento_concluido', 'Documento Concluído'), ('documento_arquivado', 'Documento Arquivado'), ('documento_devolvido', 'Documento Devolvido'), ('documento_assinado', 'Documento Assinado'), ('mensagem_nova', 'Nova Mensagem')], max_length=50, verbose_name='Tipo'),
        ),
    ]
