# Generated by Django 5.0.8 on 2025-11-05 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entrada', '0008_alter_expediente_assunto_alter_expediente_descricao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssinaturaUtilizador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assinatura_imagem', models.ImageField(help_text='Assinatura padrão do utilizador', upload_to='assinaturas/usuarios/%Y/%m/', verbose_name='Imagem da Assinatura')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('utilizador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assinatura_padrao', to=settings.AUTH_USER_MODEL, verbose_name='Utilizador')),
            ],
            options={
                'verbose_name': 'Assinatura de Utilizador',
                'verbose_name_plural': 'Assinaturas de Utilizadores',
                'ordering': ['-data_atualizacao'],
            },
        ),
        migrations.CreateModel(
            name='AssinaturaDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_assinatura', models.CharField(choices=[('canvas', 'Canvas (Mouse/Pad)'), ('upload', 'Upload de Imagem'), ('padrao', 'Assinatura Padrão')], default='canvas', max_length=20, verbose_name='Tipo de Assinatura')),
                ('assinatura_imagem', models.ImageField(upload_to='assinaturas/documentos/%Y/%m/', verbose_name='Imagem da Assinatura')),
                ('posicao_x', models.FloatField(help_text='Posição X da assinatura no documento (em pontos ou pixels)', verbose_name='Posição X')),
                ('posicao_y', models.FloatField(help_text='Posição Y da assinatura no documento (em pontos ou pixels)', verbose_name='Posição Y')),
                ('pagina', models.PositiveIntegerField(default=1, help_text='Página do documento onde a assinatura foi aplicada', verbose_name='Página')),
                ('data_assinatura', models.DateTimeField(auto_now_add=True, verbose_name='Data da Assinatura')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Endereço IP')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='User Agent')),
                ('arquivo_original_backup', models.FileField(blank=True, help_text='Backup do arquivo antes de inserir a assinatura', null=True, upload_to='expedientes/anexos/backups/%Y/%m/', verbose_name='Backup do Arquivo Original')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('certificado_digital', models.TextField(blank=True, help_text='Hash ou dados do certificado digital (para implementação futura)', null=True, verbose_name='Certificado Digital')),
                ('anexo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assinaturas', to='entrada.anexoexpediente', verbose_name='Anexo')),
                ('utilizador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assinaturas_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Utilizador')),
            ],
            options={
                'verbose_name': 'Assinatura de Documento',
                'verbose_name_plural': 'Assinaturas de Documentos',
                'ordering': ['-data_assinatura'],
                'indexes': [models.Index(fields=['anexo', '-data_assinatura'], name='assinatura__anexo_i_ebfb58_idx'), models.Index(fields=['utilizador', '-data_assinatura'], name='assinatura__utiliza_f6b469_idx')],
            },
        ),
    ]
