# Generated by Django 5.0.8 on 2025-11-05 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assinatura_digital', '0001_initial'),
        ('entrada', '0008_alter_expediente_assunto_alter_expediente_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assinaturadocumento',
            name='arquivo_original_backup',
            field=models.CharField(blank=True, help_text='Caminho do backup do arquivo antes de inserir a assinatura', max_length=500, null=True, verbose_name='Caminho do Backup do Arquivo Original'),
        ),
        migrations.CreateModel(
            name='ParecerDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Ordem do parecer na tabela (para ordenação)', verbose_name='Ordem')),
                ('data_insercao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Inserção')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('anexo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pareceres_inseridos', to='entrada.anexoexpediente', verbose_name='Anexo')),
                ('parecer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insercoes_documento', to='entrada.parecerexpediente', verbose_name='Parecer')),
            ],
            options={
                'verbose_name': 'Parecer Inserido no Documento',
                'verbose_name_plural': 'Pareceres Inseridos em Documentos',
                'ordering': ['ordem', 'data_insercao'],
                'unique_together': {('anexo', 'parecer')},
            },
        ),
    ]
