# Generated by Django 5.0.8 on 2025-11-05 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assinatura_digital', '0002_add_parecer_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='parecerdocumento',
            name='arquivo_original_backup',
            field=models.CharField(blank=True, help_text='Caminho do backup do arquivo antes de inserir pareceres (apenas no primeiro registro)', max_length=500, null=True, verbose_name='Caminho do Backup do Arquivo Original'),
        ),
    ]
